module.exports = {
  apps: [
    {
      name: 'user-api',
      cwd: './apps/user-api',
      script: 'dist/server.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: './logs/user-api-error.log',
      out_file: './logs/user-api-out.log',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
    },
    {
      name: 'vendor-api',
      cwd: './apps/vendor-api',
      script: 'dist/server.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: './logs/vendor-api-error.log',
      out_file: './logs/vendor-api-out.log',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
    },
    {
      name: 'rider-api',
      cwd: './apps/rider-api',
      script: 'dist/server.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      error_file: './logs/rider-api-error.log',
      out_file: './logs/rider-api-out.log',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
    },
    {
      name: 'admin-api',
      cwd: './apps/admin-api',
      script: 'dist/server.js',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      error_file: './logs/admin-api-error.log',
      out_file: './logs/admin-api-out.log',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '512M',
    },
    {
      name: 'socket-server',
      cwd: './libs/socket-server',
      script: 'dist/server.js',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: './logs/socket-server-error.log',
      out_file: './logs/socket-server-out.log',
      merge_logs: true,
      autorestart: true,
      max_memory_restart: '512M',
    },
  ],
};
